version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    assignees:
      - "MarekSuchanek"
    labels:
      - "dependencies"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    assignees:
      - "MarekSuchanek"
    labels:
      - "dependencies"
