name: Bug report
description: Create a report to help us improve
title: "Bug: ..."
labels: ["Bug"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the issue? Please provide information what is the problem and where it is located.
    validations:
      required: true
